# 사용한 sql문 정리하는 파일

drop table if exists member CASCADE;

create table member
(
 useridx bigint generated by default as identity,
 userid varchar(255),
 pw varchar(255),
 name varchar(255),
 email varchar(255),
 primary key (id)
);